df = pd.read_sql_query(sql_query, connect)
[2024-06-26 15:58:40,529] {subprocess.py:78} INFO - Download features 1 ...
[2024-06-26 15:58:40,529] {subprocess.py:78} INFO - {fn teradata_write_csv(/ml_data/027_rtl_deposits/in/feature.csv)}SELECT * FROM SBX_RTL.D_MLRTL_M0027_FEATURE
[2024-06-26 15:58:40,529] {subprocess.py:78} INFO - Check dates from table SBX_RTL.D_MLRTL_M0027_CTGY_1
[2024-06-26 15:58:40,531] {subprocess.py:78} INFO - Traceback (most recent call last):
[2024-06-26 15:58:40,531] {subprocess.py:78} INFO -   File "/ml_data/027_rtl_deposits/scripts/read_teradata.py", line 47, in <module>
[2024-06-26 15:58:40,531] {subprocess.py:78} INFO -     app.run(main_with_gin_config)
[2024-06-26 15:58:40,531] {subprocess.py:78} INFO -   File "/home/airflow/.local/share/virtualenvs/airflow-oRjHgsUP/lib/python3.8/site-packages/absl/app.py", line 312, in run
[2024-06-26 15:58:40,531] {subprocess.py:78} INFO -     _run_main(main, args)
[2024-06-26 15:58:40,531] {subprocess.py:78} INFO -   File "/home/airflow/.local/share/virtualenvs/airflow-oRjHgsUP/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
[2024-06-26 15:58:40,531] {subprocess.py:78} INFO -     sys.exit(main(argv))
[2024-06-26 15:58:40,531] {subprocess.py:78} INFO -   File "/ml_data/027_rtl_deposits/scripts/read_teradata.py", line 42, in main_with_gin_config
[2024-06-26 15:58:40,531] {subprocess.py:78} INFO -     main()
[2024-06-26 15:58:40,531] {subprocess.py:78} INFO -   File "/home/airflow/.local/share/virtualenvs/airflow-oRjHgsUP/lib/python3.8/site-packages/gin/config.py", line 1605, in gin_wrapper
[2024-06-26 15:58:40,531] {subprocess.py:78} INFO -     utils.augment_exception_message_and_reraise(e, err_str)
[2024-06-26 15:58:40,531] {subprocess.py:78} INFO -   File "/home/airflow/.local/share/virtualenvs/airflow-oRjHgsUP/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
[2024-06-26 15:58:40,531] {subprocess.py:78} INFO -     raise proxy.with_traceback(exception.__traceback__) from None
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -   File "/home/airflow/.local/share/virtualenvs/airflow-oRjHgsUP/lib/python3.8/site-packages/gin/config.py", line 1582, in gin_wrapper
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -     return fn(*new_args, **new_kwargs)
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -   File "/ml_data/027_rtl_deposits/scripts/read_teradata.py", line 29, in main
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -     check_dates(conn_args, tbl2, rep_dt_column_name, max_date_dif_days)
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -   File "/home/airflow/.local/share/virtualenvs/airflow-oRjHgsUP/lib/python3.8/site-packages/gin/config.py", line 1605, in gin_wrapper
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -     utils.augment_exception_message_and_reraise(e, err_str)
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -   File "/home/airflow/.local/share/virtualenvs/airflow-oRjHgsUP/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -     raise proxy.with_traceback(exception.__traceback__) from None
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -   File "/home/airflow/.local/share/virtualenvs/airflow-oRjHgsUP/lib/python3.8/site-packages/gin/config.py", line 1582, in gin_wrapper
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -     return fn(*new_args, **new_kwargs)
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -   File "/home/airflow/.local/share/virtualenvs/airflow-oRjHgsUP/lib/python3.8/site-packages/bicc_ml_pipeline/teradata/teradata_utils.py", line 107, in check_dates
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -     df = read_query_to_dataframe(conn_args, sql_stmt)
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -   File "/home/airflow/.local/share/virtualenvs/airflow-oRjHgsUP/lib/python3.8/site-packages/bicc_ml_pipeline/teradata/teradata_utils.py", line 56, in read_query_to_dataframe
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -     df = pd.read_sql_query(sql_query, connect)
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -   File "/home/airflow/.local/share/virtualenvs/airflow-oRjHgsUP/lib64/python3.8/site-packages/pandas/io/sql.py", line 397, in read_sql_query
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -     return pandas_sql.read_query(
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -   File "/home/airflow/.local/share/virtualenvs/airflow-oRjHgsUP/lib64/python3.8/site-packages/pandas/io/sql.py", line 2078, in read_query
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -     cursor = self.execute(*args)
[2024-06-26 15:58:40,532] {subprocess.py:78} INFO -   File "/home/airflow/.local/share/virtualenvs/airflow-oRjHgsUP/lib64/python3.8/site-packages/pandas/io/sql.py", line 2030, in execute
[2024-06-26 15:58:40,533] {subprocess.py:78} INFO -     raise ex from exc
[2024-06-26 15:58:40,533] {subprocess.py:78} INFO - pandas.errors.DatabaseError: Execution failed on sql 'select max(REPORT_DATE) from SBX_RTL.D_MLRTL_M0027_CTGY_1 ': [Version 17.20.0.31] [Session 54420089] [Teradata Database] [Error 5628] Column REPORT_DATE not found in SBX_RTL.D_MLRTL_M0027_CTGY_1.
